apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-fleet-poc
  namespace: fleet-default
spec:
  repo: https://github.com/aymanlinuxBoy/Rancher-fleet.git
  branch: main
  paths:
    - bundles
  recurseSubmodules: false
  forceBranch: false
